export const foodItemsList = [
  {
    id: 1,
    name: 'Guac de la Costa',
    description: 'tortillas de maïs, fruit de la passion, mango',
    amount: '7',
    stock: 20,
    quantity: 0,
    Ntype: true,
    Dtype: true,
  },
  {
    id: 2,
    name: 'Chicharron y Cerveza',
    description: 'citron vert / Corona sauce',
    amount: '7',
    stock: 20,
    quantity: 0,
    Ntype: true,
    Dtype: false,
  },
  {
    id: 3,
    name: 'Chilitos con Car',
    description: 'padrones tempura, gambas',
    amount: '10',
    stock: 20,
    quantity: 0,
    Ntype: true,
    Dtype: false,
  },
  {
    id: 4,
    name: 'Chilitos',
    description: 'padrones tempura, gambas,Corona sauce',
    amount: '6',
    stock: 20,
    quantity: 0,
    Ntype: true,
    Dtype: false,
  },
  {
    id: 5,
    name: 'con Car',
    description: 'padrones tempura, gambas,citron vert',
    amount: '5',
    stock: 20,
    quantity: 0,
    Ntype: true,
    Dtype: false,
  },
];
export const HitSlop = {
  right: 15,
  left: 15,
  bottom: 15,
  top: 15,
};
